import StyleDictionary from 'style-dictionary';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import fs from 'node:fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const tokensPath = path.join(__dirname, '..', 'tokens', 'tokens.json');

// Custom formatter: emits a typed TypeScript ES module from the token dictionary.
// The output is `export const tokens = { ... } as const` so consumers get
// full literal-type inference. Existing JSON/iOS/Android/CSS outputs are unchanged.
//
// Note: the source tokens.json does not use Style Dictionary's `{ value: ... }`
// leaf format, so `dictionary.tokens` is used to pass the raw tree through intact.
StyleDictionary.registerFormat({
  name: 'typescript/es6-as-const',
  formatter: ({ dictionary }) => {
    // Strip Style Dictionary's internal metadata properties before serialising.
    function stripMeta(node) {
      if (typeof node !== 'object' || node === null) return node;
      const out = {};
      for (const [key, value] of Object.entries(node)) {
        if (key.startsWith('$') || key === 'attributes' || key === 'comment') continue;
        out[key] = stripMeta(value);
      }
      return out;
    }

    const clean = stripMeta(dictionary.tokens);
    const json = JSON.stringify(clean, null, 2);
    return `// Auto-generated by Style Dictionary — do not edit manually.\nexport const tokens = ${json} as const;\nexport type Tokens = typeof tokens;\n`;
  },
});

StyleDictionary.extend({
  source: [tokensPath],
  platforms: {
    json: {
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.json',
          format: 'json',
        },
      ],
    },
    typescript: {
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.ts',
          format: 'typescript/es6-as-const',
        },
      ],
    },
    iosSwift: {
      transformGroup: 'ios-swift',
      buildPath: 'dist/ios/',
      files: [
        {
          destination: 'DesignTokens.swift',
          format: 'ios-swift/class.swift',
          className: 'DesignTokens',
        },
      ],
    },
    androidXml: {
      transformGroup: 'android',
      buildPath: 'dist/android/',
      files: [
        {
          destination: 'tokens.colors.xml',
          format: 'android/resources',
        },
      ],
    },
    webCss: {
      transformGroup: 'css',
      buildPath: 'dist/web/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          options: {
            outputReferences: true,
          },
        },
      ],
    },
  },
}).buildAllPlatforms();

// Copy the TypeScript tokens directly into the app package so Metro
// never has to resolve across package boundaries at runtime.
const appTokensDest = path.resolve(__dirname, '../../../app/src/design/tokens.ts');
const appTokensSrc = path.resolve(__dirname, '../dist/tokens.ts');
fs.copyFileSync(appTokensSrc, appTokensDest);
console.log(`Copied tokens.ts → ${appTokensDest}`);
