import StyleDictionary from 'style-dictionary';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import fs from 'node:fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const tokensPath = path.join(__dirname, '..', 'tokens', 'tokens.json');

// Read the raw tokens.json file
const rawTokens = JSON.parse(fs.readFileSync(tokensPath, 'utf8'));

// Inject a dummy token with a value key so Style Dictionary v4/v5 is satisfied that tokens exist and builds the files.
const tokensWithDummy = {
  ...rawTokens,
  dummy_for_sd: { value: 'dummy' }
};

const sd = new StyleDictionary({
  // Use inline tokens instead of the source path directly
  tokens: tokensWithDummy,
  hooks: {
    formats: {
      'custom/json': () => {
        function stripMeta(node) {
          if (typeof node !== 'object' || node === null) return node;
          const out = {};
          for (const [key, value] of Object.entries(node)) {
            if (key.startsWith('$') || key === 'attributes' || key === 'comment' || key === 'dummy_for_sd') continue;
            out[key] = stripMeta(value);
          }
          return out;
        }
        const clean = stripMeta(rawTokens);
        return JSON.stringify(clean, null, 2);
      },
      'typescript/es6-as-const': () => {
        // Strip Style Dictionary's internal metadata properties before serialising.
        function stripMeta(node) {
          if (typeof node !== 'object' || node === null) return node;
          const out = {};
          for (const [key, value] of Object.entries(node)) {
            if (key.startsWith('$') || key === 'attributes' || key === 'comment' || key === 'dummy_for_sd') continue;
            out[key] = stripMeta(value);
          }
          return out;
        }

        const clean = stripMeta(rawTokens);
        const json = JSON.stringify(clean, null, 2);
        return `// Auto-generated by Style Dictionary — do not edit manually.\nexport const tokens = ${json} as const;\nexport type Tokens = typeof tokens;\n`;
      },
    },
  },
  platforms: {
    json: {
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.json',
          format: 'custom/json',
        },
      ],
    },
    typescript: {
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.ts',
          format: 'typescript/es6-as-const',
        },
      ],
    },
    iosSwift: {
      transformGroup: 'ios-swift',
      buildPath: 'dist/ios/',
      files: [
        {
          destination: 'DesignTokens.swift',
          format: 'ios-swift/class.swift',
          className: 'DesignTokens',
        },
      ],
    },
    androidXml: {
      transformGroup: 'android',
      buildPath: 'dist/android/',
      files: [
        {
          destination: 'tokens.colors.xml',
          format: 'android/resources',
        },
      ],
    },
    webCss: {
      transformGroup: 'css',
      buildPath: 'dist/web/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          options: {
            outputReferences: true,
          },
        },
      ],
    },
  },
});

// Build all platforms asynchronously (Style Dictionary v4+)
await sd.buildAllPlatforms();

// Copy the TypeScript tokens directly into the app package so Metro
// never has to resolve across package boundaries at runtime.
const appTokensDest = path.resolve(__dirname, '../../../app/src/design/tokens.ts');
const appTokensSrc = path.resolve(__dirname, '../dist/tokens.ts');
fs.copyFileSync(appTokensSrc, appTokensDest);
console.log(`Copied tokens.ts → ${appTokensDest}`);
