// Imports the TypeScript design token output generated by Style Dictionary.
// This file is copied here by `make tokens` (build.js) — do not edit manually.
// Run `make tokens` from mobile/ to regenerate if tokens.json changes.
import { tokens } from './tokens';

export type Theme = typeof tokens.themes.default;

/**
 * Returns the default design theme object derived from the shared token source.
 * Kept as a plain function in Sprint 0; a React hook wrapper will be added in
 * Sprint 1 when theming context is introduced.
 */
export function useTheme(): Theme {
  return tokens.themes.default;
}
